name       : webvfx
version    : 0.4.4
release    : 5
source     :
    - git|https://github.com/mltframework/webvfx.git : d65a42d25a887d11fd5cf5e485c1561dc802b671
    - https://github.com/mltframework/mlt/releases/download/v6.6.0/mlt-6.6.0.tar.gz : 28cbc5974f72ef228d624a58809c7c8055372f5f62f5882dc055099d444b2cdd
license    : BSD-3-Clause
component  : multimedia.library
summary    : Video effects library
description: |
    WebVfx is a video effects library that allows effects to be implemented using WebKit HTML or Qt QML.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt-framework)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
setup      : |
    tar xf $sources/mlt-6.6.0.tar.gz -C .
    %qmake PREFIX=$installdir/usr MLT_SOURCE=$workdir/mlt-6.6.0
build      : |
    %make
install    : |
    %make_install
