name       : webvfx
version    : 1.1.0
release    : 6
source     :
    - https://github.com/mltframework/webvfx/releases/download/1.1.0/webvfx-1.1.0.txz : 49ce670e573d9d259b90913edca10378ad3bc19613283eb99baa6eb9cc6d4394
license    : BSD-3-Clause
component  : multimedia.library
summary    : Video effects library
description: |
    WebVfx is a video effects library that allows effects to be implemented using WebKit HTML or Qt QML.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt-framework)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
