name       : webvfx
version    : 0.4.4
release    : 3
source     :
    - git|https://github.com/mltframework/webvfx.git : e918ce4667e623c3d60735cb898223e730c6d7af
    - https://github.com/mltframework/mlt/archive/v6.4.1.tar.gz : 87583af552695b2235f4ee3fc1e645d69e31702b109331d7e8785fb180cfa382
license    : BSD-3-Clause
component  : multimedia.library
summary    : Video effects library
description: |
    WebVfx is a video effects library that allows effects to be implemented using WebKit HTML or Qt QML.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(mlt-framework)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
setup      : |
    tar xf $sources/v6.4.1.tar.gz -C .
    pushd mlt-6.4.1
        %patch -p1 < $pkgfiles/0001-Fix-glibc-2.26-build.patch
    popd
    %qmake PREFIX=$installdir/usr MLT_SOURCE=$workdir/mlt-6.4.1
build      : |
    %make
install    : |
    %make_install
